### ISSUE TITLE
RuntimeError: Timeout setting Mode

### ISSUE THREAD

**Issue by RahndelDaVandal** [adafruit/Adafruit_CircuitPython_MCP2515#13]
I am trying to use the MCP2515 with my BlueSense Feather and rp2040 feather. I ran your simple test code and it fails to initialize on 4 different MCP2515 boards. Any suggestions or should I just forget about the MCP2515 and suck it up and buy some feather cans.

Traceback (most recent call last):
  File "code.py", line 16, in <module>
  File "adafruit_mcp2515/__init__.py", line 270, in __init__
  File "adafruit_mcp2515/__init__.py", line 302, in initialize
  File "adafruit_mcp2515/__init__.py", line 631, in _set_mode
  File "adafruit_mcp2515/__init__.py", line 650, in _request_new_mode
RuntimeError: Timeout setting Mode

**Comment by Borti0** [comment]
I have the same problem, for the moment I am trying to solve it, the problem is that the new operating mode in mcp2515 fails to be written, and when reading for validation the configuration mode is returned which is set to activate once the power is turned on. mcp2515

**Comment by Borti0** [comment]
You may have found a solution for the _BITMOD constant instead of 0x05 trying to put 0x50. I'll be back after a few tests.

**Comment by fy8207345** [comment]
I have the same problem on my Raspberry 4b.
the wirings is below:
MCp2515 vcc -> raspberry 5v
MCp2515 GND -> raspberry GND
MCp2515 CS-> raspberry GPIO25
MCp2515 SO-> raspberry GPIO9
MCp2515 SI-> raspberry GPIO10
MCp2515 SCK -> raspberry GPIO11
MCp2515 INT -> raspberry GPIO8

**Comment by fy8207345** [comment]
After comparing this library and the code in: https://github.com/autowp/arduino-mcp2515/blob/master/mcp2515.cpp.
When i commented the line 362 in the initialize function. It worked. The code finally look like this.
![a](https://user-images.githubusercontent.com/8471378/227898449-3ce4829c-5859-47d7-aa64-d4e04f356c71.png)

**Comment by HourGlss** [comment]
Still have this problem.

**Comment by anecdata** [comment]
Note that this is the exception that arises if the `CS` pin in code doesn't match the wiring:

Correct `CS` pin:
```py
Adafruit CircuitPython 7.3.3 on 2022-08-29; Adafruit Feather RP2040 with rp2040
>>> from time import sleep
>>> import board
>>> from digitalio import DigitalInOut
>>> from adafruit_mcp2515.canio import Message, RemoteTransmissionRequest
>>> from adafruit_mcp2515 import MCP2515 as CAN
>>> 
>>> cs = DigitalInOut(board.D5)
>>> cs.switch_to_output()
>>> spi = board.SPI()
>>> 
>>> can_bus = CAN(spi, cs)
>>> 
```
Wrong `CS` pin:
```py
Adafruit CircuitPython 7.3.3 on 2022-08-29; Adafruit Feather RP2040 with rp2040
>>> from time import sleep
>>> import board
>>> from digitalio import DigitalInOut
>>> from adafruit_mcp2515.canio import Message, RemoteTransmissionRequest
>>> from adafruit_mcp2515 import MCP2515 as CAN
>>> 
>>> cs = DigitalInOut(board.D4)
>>> cs.switch_to_output()
>>> spi = board.SPI()
>>> 
>>> can_bus = CAN(spi, cs)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_mcp2515/__init__.py", line 322, in __init__
  File "adafruit_mcp2515/__init__.py", line 354, in initialize
  File "adafruit_mcp2515/__init__.py", line 687, in _set_mode
  File "adafruit_mcp2515/__init__.py", line 706, in _request_new_mode
RuntimeError: Timeout setting Mode
>>> 
```

**Comment by yarrumretep** [comment]
Having this problem with CS pin D5 - any thoughts @anecdata ?

```python
Adafruit CircuitPython 8.2.8 on 2023-11-16; Adafruit Feather RP2040 CAN with rp2040
>>> from time import sleep
>>> import board
>>> from digitalio import DigitalInOut
>>> from adafruit_mcp2515 import MCP2515 as CAN
>>> cs = DigitalInOut(board.D5)
>>> cs.switch_to_output()
>>> spi = board.SPI()
>>> can_bus = CAN(spi, cs)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_mcp2515/__init__.py", line 322, in __init__
  File "adafruit_mcp2515/__init__.py", line 354, in initialize
  File "adafruit_mcp2515/__init__.py", line 687, in _set_mode
  File "adafruit_mcp2515/__init__.py", line 706, in _request_new_mode
RuntimeError: Timeout setting Mode
```

**Comment by anecdata** [comment]
@yarrumretep I don't have that board, but the guide says `CS` is:
> GPIO19 - CAN Chip Select pin. Can be accessed in CircuitPython with CAN_CS and in Arduino with PIN_CAN_CS.
https://learn.adafruit.com/adafruit-rp2040-can-bus-feather/pinouts (about 2/3 down the page)
